name: Linux / Foss Group Linz
description: The official website of the Linux & FOSS Group Linz
url: https://linuxfosslinz.github.io
author: SIMULATAN
timezone: Europe/Vienna
timezone_short: AT

keywords: ['linux', 'foss', 'linz', 'meetup', 'linux meetup', 'FOSS meetup', 'linux group linz', 'foss group linz', 'linux foss group linz']

host: 0.0.0.0

sass:
  sass_dir: _sass
  style: expanded # compact, expanded or compressed

pagination:
  enabled: true
  per_page: 10
  sort_field: 'date'
  sort_reverse: true

exclude: [ 'README.md', 'COPYING' ]

plugins:
  - jekyll-feed
  - jekyll-paginate-v2
  - jekyll-seo-tag

